/**
 * Checks the PDF the 2D Net view hands out — for every solid, both papers and
 * three net heights — by reading the generated bytes back.
 *
 * The interesting assertion is the physical one. The script measures every path
 * segment inside a page's content stream, converts it back to millimetres and
 * compares it with the net's edge lengths from `netMeasurement`. That is what
 * "true size" means: a printed sheet is only foldable if 1 mm of panel is 1 mm
 * of paper, and a PDF that quietly scaled the drawing to fit would still open
 * perfectly in every reader. The rest is the structural contract — xref offsets
 * that land on their object headers, `/Length` matching the stream, MediaBox
 * equal to the chosen paper, ASCII-only bytes (offsets are byte counts), and
 * escaped text strings.
 *
 *   node test-netpdf.mjs
 */
import { registerHooks } from "node:module";

// The app's modules import each other without file extensions (bundler style),
// which Node's own resolver will not follow. Hooks have to be registered before
// the first import of them, so those imports are dynamic below.
registerHooks({
  resolve(specifier, context, nextResolve) {
    try {
      return nextResolve(specifier, context);
    } catch (error) {
      if (specifier.startsWith(".")) {
        for (const suffix of [".ts", ".tsx", "/index.ts"]) {
          try {
            return nextResolve(specifier + suffix, context);
          } catch {
            /* try the next suffix */
          }
        }
      }
      throw error;
    }
  },
});

const { buildNetPdf, netPdfFileName, planSheets, PAPER_MM, PT_PER_MM } = await import(
  "./app/generator/components/netPdf.ts"
);
const { computeNet } = await import("./app/generator/components/polyhedronNetUtils.ts");
const { fitFromMeasurement, measureNet } = await import("./app/generator/components/netMeasurement.ts");

const SHAPES = [
  "Tetrahedron",
  "Cube",
  "Octahedron",
  "Dodecahedron",
  "Icosahedron",
  "Truncated Cube",
  "Truncated Icosahedron",
  "Prism",
  "Pyramid",
];
const PAPERS = ["A4", "A3"];
const UNITS = ["mm", "cm"];
const HEIGHTS = [40, 120, 275];

let checks = 0;
const failures = [];
const ok = (condition, label) => {
  checks += 1;
  if (!condition) failures.push(label);
  return condition;
};

const latin1 = (bytes) => Buffer.from(bytes).toString("latin1");
const segmentLength = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);

/** Offset of every object header ("N 0 obj") in the file. */
function objectOffsets(file) {
  const found = new Map();
  for (const match of file.matchAll(/(?:^|\n)(\d+) 0 obj/g)) {
    found.set(Number(match[1]), match.index + (match[0][0] === "\n" ? 1 : 0));
  }
  return found;
}

/** Walks the xref table and checks that each entry points at its object header. */
function checkXref(file, offsets, label) {
  const startxref = Number(file.slice(file.lastIndexOf("startxref") + 9).trim().split(/\s+/)[0]);
  const lines = file.slice(startxref).split("\n");
  ok(lines[0] === "xref", `${label}: "xref" where startxref points`);
  const size = Number(lines[1].split(" ")[1]);
  ok(Number.isFinite(size) && size > 1, `${label}: xref subsection header`);
  for (let id = 0; id < size; id++) {
    // An entry is exactly 20 bytes on disk; splitting on "\n" leaves the trailing
    // space of " \n" in the line, so 19 characters is the whole field.
    const entry = lines[2 + id];
    if (!ok(typeof entry === "string" && /^\d{10} \d{5} [nf] $/.test(entry), `${label}: xref entry ${id} is well formed`)) break;
    const offset = Number(entry.slice(0, 10));
    if (id === 0) {
      ok(offset === 0 && entry[17] === "f", `${label}: entry 0 is the free entry`);
    } else {
      ok(offset === offsets.get(id), `${label}: entry ${id} points at "${id} 0 obj"`);
    }
  }
}


/** Page dictionaries and their content streams. */
function pagesOf(file, offsets) {
  const pages = [];
  for (const line of file.split("\n")) {
    const match =
      /^<< \/Type \/Page \/Parent 2 0 R \/MediaBox \[0 0 ([\d.]+) ([\d.]+)\] \/Resources << \/Font .*\/Contents (\d+) 0 R >>$/.exec(
        line
      );
    if (!match) continue;
    const contentId = Number(match[3]);
    const head = file.slice(offsets.get(contentId));
    const declared = /\n<< \/Length (\d+) >>\nstream\n/.exec(head);
    if (!declared) continue;
    const length = Number(declared[1]);
    const from = offsets.get(contentId) + declared.index + declared[0].length;
    const content = file.slice(from, from + length);
    const closed = file.slice(from + length, from + length + 11) === "\nendstream\n";
    pages.push({ wPt: Number(match[1]), hPt: Number(match[2]), content, closed });
  }
  return pages;
}

/**
 * Every segment of a content stream, in millimetres. The drawing code writes one
 * path per line ("x y m x y l ... h" then the paint operator), which is all this
 * has to read; millimetres come back through the same 72/25.4 pt-per-mm the
 * writer used.
 */
function segmentsMm(content) {
  const lengths = [];
  const points = [];
  const segments = [];
  for (const line of content.split("\n")) {
    const pts = [...line.matchAll(/(-?\d+(?:\.\d+)?) (-?\d+(?:\.\d+)?) ([ml])/g)].map((m) => ({
      x: Number(m[1]) / PT_PER_MM,
      y: Number(m[2]) / PT_PER_MM,
    }));
    if (pts.length < 2) continue;
    points.push(...pts);
    const push = (a, b) => {
      lengths.push(segmentLength(a, b));
      segments.push({ ax: a.x, ay: a.y, bx: b.x, by: b.y });
    };
    for (let i = 1; i < pts.length; i++) push(pts[i - 1], pts[i]);
    if (line.trimEnd().endsWith("h")) push(pts[pts.length - 1], pts[0]);
  }
  return { lengths, points, segments };
}

const bboxOf = (points) => {
  const xs = points.map((p) => p.x);
  const ys = points.map((p) => p.y);
  return { w: Math.max(...xs) - Math.min(...xs), h: Math.max(...ys) - Math.min(...ys) };
};

/** The physical sizes the PDF must contain: face edges plus flap hinge and depth. */
function expectedGeometry(shape, scale) {
  const net = computeNet(shape);
  const lengths = [];
  const points = [];
  const push = (a, b) => lengths.push(segmentLength(a, b) * scale);
  for (const poly of net.polygons) {
    for (let i = 0; i < poly.length; i++) push(poly[i], poly[(i + 1) % poly.length]);
    points.push(...poly);
  }
  for (const tab of net.tabs ?? []) {
    push(tab.pts[0], tab.pts[1]); // hinge
    push(tab.pts[1], tab.pts[2]); // flap depth
    points.push(...tab.pts);
  }
  return { lengths, bbox: bboxOf(points.map((p) => ({ x: p.x * scale, y: p.y * scale }))) };
}

const nearest = (value, candidates) => candidates.reduce((best, c) => Math.min(best, Math.abs(c - value)), Infinity);

/* --- does the caption really stay out of the net's way? ------------------- */

const cross2 = (ox, oy, ax, ay, bx, by) => (ax - ox) * (by - oy) - (ay - oy) * (bx - ox);

/** True when a segment touches, crosses or lies inside an axis-aligned rect. */
function segmentHitsRect(seg, r) {
  const inside = (x, y) => x >= r.x && x <= r.x + r.w && y >= r.y && y <= r.y + r.h;
  if (inside(seg.ax, seg.ay) || inside(seg.bx, seg.by)) return true;
  if (Math.abs(seg.ax - seg.bx) < 1e-9 && Math.abs(seg.ay - seg.by) < 1e-9) return false;
  const corners = [
    [r.x, r.y],
    [r.x + r.w, r.y],
    [r.x + r.w, r.y + r.h],
    [r.x, r.y + r.h],
  ];
  return corners.some(([cx, cy], i) => {
    const [dx, dy] = corners[(i + 1) % corners.length];
    const d1 = cross2(cx, cy, dx, dy, seg.ax, seg.ay);
    const d2 = cross2(cx, cy, dx, dy, seg.bx, seg.by);
    const d3 = cross2(seg.ax, seg.ay, seg.bx, seg.by, cx, cy);
    const d4 = cross2(seg.ax, seg.ay, seg.bx, seg.by, dx, dy);
    const straddles = (p, q) => (p > 0 && q < 0) || (p < 0 && q > 0) || p === 0 || q === 0;
    return straddles(d1, d2) && straddles(d3, d4);
  });
}

/** The caption's white box: the first closed path drawn after the net's clip is popped. */
function captionBoxMm(content) {
  const after = content.split("\nQ\n").slice(1).join("\nQ\n");
  for (const line of after.split("\n")) {
    if (!line.trimEnd().endsWith("h")) continue;
    const pts = [...line.matchAll(/(-?\d+(?:\.\d+)?) (-?\d+(?:\.\d+)?) ([ml])/g)].map((m) => ({
      x: Number(m[1]) / PT_PER_MM,
      y: Number(m[2]) / PT_PER_MM,
    }));
    if (pts.length !== 4) continue;
    const xs = pts.map((p) => p.x);
    const ys = pts.map((p) => p.y);
    return { x: Math.min(...xs), y: Math.min(...ys), w: Math.max(...xs) - Math.min(...xs), h: Math.max(...ys) - Math.min(...ys) };
  }
  return null;
}


let pdfPages = 0;
let pdfBytes = 0;
let crowdedCaptions = 0;

for (const shape of SHAPES) {
  const measurement = measureNet(shape);
  if (!ok(!!measurement, `${shape}: measurable`)) continue;

  for (const paper of PAPERS) {
    for (const unit of UNITS) {
      for (const height of HEIGHTS) {
        const label = `${shape} | ${paper} | ${unit} | ${height}mm`;
        const fit = fitFromMeasurement(measurement, shape, height);
        if (!ok(!!fit, `${label}: fit`)) continue;

        const bytes = buildNetPdf({ selected: shape, fit, paper, unit });
        if (!ok(!!bytes, `${label}: builds`)) continue;
        pdfBytes += bytes.length;
        const file = latin1(bytes);

        ok(file.startsWith("%PDF-1.4\n"), `${label}: PDF header`);
        ok(file.endsWith("%%EOF\n"), `${label}: %%EOF`);
        ok(
          [...bytes].every((b) => b < 0x80),
          `${label}: ASCII only (character counts are byte offsets)`
        );

        const offsets = objectOffsets(file);
        checkXref(file, offsets, label);

        // Sheet plan: the count the panel prints, and the coverage the tiling needs.
        const layout = planSheets(fit.netWidthMm, fit.netHeightMm, paper);
        const legacy = Math.max(
          1,
          Math.min(
            Math.ceil(fit.netWidthMm / PAPER_MM[paper].w) * Math.ceil(fit.netHeightMm / PAPER_MM[paper].h),
            Math.ceil(fit.netWidthMm / PAPER_MM[paper].h) * Math.ceil(fit.netHeightMm / PAPER_MM[paper].w)
          )
        );
        ok(layout.pages === legacy, `${label}: page count matches the panel's (${layout.pages})`);
        ok(
          (layout.cols - 1) * layout.sheetWmm - layout.shiftXmm + layout.sheetWmm >= fit.netWidthMm - 1e-9 &&
            (layout.rows - 1) * layout.sheetHmm - layout.shiftYmm + layout.sheetHmm >= fit.netHeightMm - 1e-9,
          `${label}: sheets cover the whole net`
        );
        ok(layout.shiftXmm >= 0 && layout.shiftYmm >= 0, `${label}: no negative shift`);
        ok(
          Math.min(layout.sheetWmm, layout.sheetHmm) === PAPER_MM[paper].w &&
            Math.max(layout.sheetWmm, layout.sheetHmm) === PAPER_MM[paper].h,
          `${label}: sheets are ${paper}`
        );

        const pages = pagesOf(file, offsets);
        pdfPages += pages.length;
        ok(pages.length === layout.pages, `${label}: ${pages.length} page(s) as planned`);

        const expected = expectedGeometry(shape, fit.scale);
        const paperMm = [
          Math.min(PAPER_MM[paper].w, PAPER_MM[paper].h),
          Math.max(PAPER_MM[paper].w, PAPER_MM[paper].h),
        ];

        for (const [index, page] of pages.entries()) {
          const sheet = `${label} | sheet ${index + 1}/${pages.length}`;
          ok(page.closed, `${sheet}: stream length matches /Length`);
          // The sheet is the paper size in the orientation the plan chose.
          const [short, long] = [page.wPt / PT_PER_MM, page.hPt / PT_PER_MM].sort((a, b) => a - b);
          ok(
            Math.abs(short - paperMm[0]) < 0.01 && Math.abs(long - paperMm[1]) < 0.01,
            `${sheet}: MediaBox is ${paper} (${short.toFixed(0)}x${long.toFixed(0)} mm)`
          );
          ok(
            layout.landscape ? page.wPt > page.hPt : page.wPt < page.hPt,
            `${sheet}: MediaBox orientation matches the plan`
          );

          // Everything before the sheet clip is popped is the net itself; the
          // caption box and its scale bar follow it.
          const ink = page.content.split("\nQ\n")[0];
          const { lengths, points, segments } = segmentsMm(ink);
          ok(lengths.length > 0, `${sheet}: net is drawn`);

          const box = captionBoxMm(page.content);
          if (ok(!!box, `${sheet}: caption box found`)) {
            // Independently look at all four corners the writer may choose: the
            // caption has to take a blank one, or — when the net fills the sheet
            // — the corner with the fewest lines crossing it.
            const inset = 3.5;
            const w = box.w;
            const h = box.h;
            const corners = [
              { x: inset, y: inset },
              { x: page.wPt / PT_PER_MM - inset - w, y: inset },
              { x: inset, y: page.hPt / PT_PER_MM - inset - h },
              { x: page.wPt / PT_PER_MM - inset - w, y: page.hPt / PT_PER_MM - inset - h },
            ];
            const counts = corners.map((c) => segments.filter((seg) => segmentHitsRect(seg, { ...c, w, h })).length);
            const best = Math.min(...counts);
            const covered = segments.filter((seg) => segmentHitsRect(seg, box)).length;
            if (best > 0) crowdedCaptions += 1;
            ok(
              covered === best,
              `${sheet}: caption took the clearest corner (${covered} crossed, best available ${best})`
            );
          }

          const bbox = bboxOf(points);
          ok(
            Math.abs(bbox.w - expected.bbox.w) < 0.05 && Math.abs(bbox.h - expected.bbox.h) < 0.05,
            `${sheet}: drawn ${bbox.w.toFixed(2)}x${bbox.h.toFixed(2)} mm, expected ${expected.bbox.w.toFixed(2)}x${expected.bbox.h.toFixed(2)}`
          );

          const wrong = lengths.filter((len) => nearest(len, expected.lengths) > 0.05);
          ok(
            wrong.length === 0,
            `${sheet}: every segment is a real edge length (${wrong.length} off, first ${wrong[0]?.toFixed(2)} mm)`
          );

          const withoutStrings = ink.replace(/\(((?:[^()\\]|\\.)*)\) Tj/g, "");
          ok(!withoutStrings.includes("(") && !withoutStrings.includes(")"), `${sheet}: text strings escaped`);

          const caption = [...page.content.matchAll(/\(((?:[^()\\]|\\.)*)\) Tj/g)].map((m) => m[1]);
          ok(caption.some((t) => t.includes(shape)), `${sheet}: caption names the solid`);
          ok(caption.some((t) => t.includes(` ${unit}`)), `${sheet}: caption uses ${unit}`);
          ok(caption.some((t) => t.includes(`Sheet ${index + 1} of ${pages.length}`)), `${sheet}: caption numbers the sheet`);
          ok(caption.every((t) => /^[\x20-\x7e]*$/.test(t)), `${sheet}: caption text is printable ASCII`);
        }

        const name = netPdfFileName(shape, height, unit, paper);
        ok(
          /^LetsPoly-[a-z0-9-]+-net-[\d.]+(mm|cm)-(A4|A3)\.pdf$/.test(name),
          `${label}: file name is web-safe (${name})`
        );
      }
    }
  }
}

console.log(`checked ${checks} assertions across ${SHAPES.length} solids`);
console.log(`pages generated: ${pdfPages}, ${Math.round(pdfBytes / 1024)} kB of PDF`);
console.log(`sheets with no blank corner for the caption: ${crowdedCaptions}/${pdfPages}`);
if (failures.length) {
  console.log(`\n${failures.length} FAILED:`);
  for (const failure of failures.slice(0, 25)) console.log(` - ${failure}`);
  process.exit(1);
}
console.log("all good");
